# Generated by Django 4.2.1 on 2023-05-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocalHUB', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='../../images/'),
        ),
    ]
